/*
 * ApproveAPISwagger
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.approveapi;

import java.util.Objects;
import java.util.Arrays;
import com.approveapi.PromptMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * CreatePromptRequest
 */

public class CreatePromptRequest {
  @JsonProperty("body")
  private String body;

  @JsonProperty("title")
  private String title;

  @JsonProperty("reject_text")
  private String rejectText;

  @JsonProperty("expires_in")
  private BigDecimal expiresIn;

  @JsonProperty("long_poll")
  private Boolean longPoll;

  @JsonProperty("user")
  private String user;

  @JsonProperty("approve_text")
  private String approveText;

  @JsonProperty("metadata")
  private PromptMetadata metadata = null;

  public CreatePromptRequest body(String body) {
    this.body = body;
    return this;
  }

   /**
   * The body of the approval request to show the user.
   * @return body
  **/
  @ApiModelProperty(required = true, value = "The body of the approval request to show the user.")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public CreatePromptRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of an approval request. Defaults to an empty string.
   * @return title
  **/
  @ApiModelProperty(value = "The title of an approval request. Defaults to an empty string.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CreatePromptRequest rejectText(String rejectText) {
    this.rejectText = rejectText;
    return this;
  }

   /**
   * The reject action text. Defaults to &#39;Reject&#39;.
   * @return rejectText
  **/
  @ApiModelProperty(value = "The reject action text. Defaults to 'Reject'.")
  public String getRejectText() {
    return rejectText;
  }

  public void setRejectText(String rejectText) {
    this.rejectText = rejectText;
  }

  public CreatePromptRequest expiresIn(BigDecimal expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * The number of seconds until this request can no longer be answered.
   * @return expiresIn
  **/
  @ApiModelProperty(value = "The number of seconds until this request can no longer be answered.")
  public BigDecimal getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(BigDecimal expiresIn) {
    this.expiresIn = expiresIn;
  }

  public CreatePromptRequest longPoll(Boolean longPoll) {
    this.longPoll = longPoll;
    return this;
  }

   /**
   * If true, the request waits (long-polls) until the user responds to the prompt or more than 10 minutes pass. Defaults to false.
   * @return longPoll
  **/
  @ApiModelProperty(value = "If true, the request waits (long-polls) until the user responds to the prompt or more than 10 minutes pass. Defaults to false.")
  public Boolean getLongPoll() {
    return longPoll;
  }

  public void setLongPoll(Boolean longPoll) {
    this.longPoll = longPoll;
  }

  public CreatePromptRequest user(String user) {
    this.user = user;
    return this;
  }

   /**
   * The user to send the approval request to. Can be either an email address or a phone number.
   * @return user
  **/
  @ApiModelProperty(required = true, value = "The user to send the approval request to. Can be either an email address or a phone number.")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public CreatePromptRequest approveText(String approveText) {
    this.approveText = approveText;
    return this;
  }

   /**
   * The approve action text. Defaults to &#39;Approve&#39;.
   * @return approveText
  **/
  @ApiModelProperty(value = "The approve action text. Defaults to 'Approve'.")
  public String getApproveText() {
    return approveText;
  }

  public void setApproveText(String approveText) {
    this.approveText = approveText;
  }

  public CreatePromptRequest metadata(PromptMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public PromptMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(PromptMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePromptRequest createPromptRequest = (CreatePromptRequest) o;
    return Objects.equals(this.body, createPromptRequest.body) &&
        Objects.equals(this.title, createPromptRequest.title) &&
        Objects.equals(this.rejectText, createPromptRequest.rejectText) &&
        Objects.equals(this.expiresIn, createPromptRequest.expiresIn) &&
        Objects.equals(this.longPoll, createPromptRequest.longPoll) &&
        Objects.equals(this.user, createPromptRequest.user) &&
        Objects.equals(this.approveText, createPromptRequest.approveText) &&
        Objects.equals(this.metadata, createPromptRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, title, rejectText, expiresIn, longPoll, user, approveText, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePromptRequest {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    rejectText: ").append(toIndentedString(rejectText)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    longPoll: ").append(toIndentedString(longPoll)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    approveText: ").append(toIndentedString(approveText)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

