/*
 * ApproveAPISwagger
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.approveapi;

import java.util.Objects;
import java.util.Arrays;
import com.approveapi.PromptAnswer;
import com.approveapi.PromptMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Prompt
 */

public class Prompt {
  @JsonProperty("answer")
  private PromptAnswer answer = null;

  @JsonProperty("sent_at")
  private BigDecimal sentAt;

  @JsonProperty("id")
  private String id;

  @JsonProperty("expires_at")
  private BigDecimal expiresAt;

  @JsonProperty("metadata")
  private PromptMetadata metadata = null;

  public Prompt answer(PromptAnswer answer) {
    this.answer = answer;
    return this;
  }

   /**
   * Get answer
   * @return answer
  **/
  @ApiModelProperty(value = "")
  public PromptAnswer getAnswer() {
    return answer;
  }

  public void setAnswer(PromptAnswer answer) {
    this.answer = answer;
  }

  public Prompt sentAt(BigDecimal sentAt) {
    this.sentAt = sentAt;
    return this;
  }

   /**
   * The unix timestamp when this prompt was sent.
   * @return sentAt
  **/
  @ApiModelProperty(required = true, value = "The unix timestamp when this prompt was sent.")
  public BigDecimal getSentAt() {
    return sentAt;
  }

  public void setSentAt(BigDecimal sentAt) {
    this.sentAt = sentAt;
  }

  public Prompt id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique id for this prompt.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "A unique id for this prompt.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Prompt expiresAt(BigDecimal expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * The unix timestamp when this prompt can no longer be answered.
   * @return expiresAt
  **/
  @ApiModelProperty(value = "The unix timestamp when this prompt can no longer be answered.")
  public BigDecimal getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(BigDecimal expiresAt) {
    this.expiresAt = expiresAt;
  }

  public Prompt metadata(PromptMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public PromptMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(PromptMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Prompt prompt = (Prompt) o;
    return Objects.equals(this.answer, prompt.answer) &&
        Objects.equals(this.sentAt, prompt.sentAt) &&
        Objects.equals(this.id, prompt.id) &&
        Objects.equals(this.expiresAt, prompt.expiresAt) &&
        Objects.equals(this.metadata, prompt.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answer, sentAt, id, expiresAt, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Prompt {\n");
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("    sentAt: ").append(toIndentedString(sentAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

