/*
 * ApproveAPISwagger
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.approveapi;

import com.approveapi.PromptAnswer;
import com.approveapi.PromptMetadata;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Prompt
 */
public class PromptTest {
    private final Prompt model = new Prompt();

    /**
     * Model tests for Prompt
     */
    @Test
    public void testPrompt() {
        // TODO: test Prompt
    }

    /**
     * Test the property 'answer'
     */
    @Test
    public void answerTest() {
        // TODO: test answer
    }

    /**
     * Test the property 'sentAt'
     */
    @Test
    public void sentAtTest() {
        // TODO: test sentAt
    }

    /**
     * Test the property 'isExpired'
     */
    @Test
    public void isExpiredTest() {
        // TODO: test isExpired
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
