/*
 * ApproveAPISwagger
 * The simple API to request a user's approval on anything via email + sms.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@approveapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.approveapi;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PromptStatus
 */
public class PromptStatusTest {
    private final PromptStatus model = new PromptStatus();

    /**
     * Model tests for PromptStatus
     */
    @Test
    public void testPromptStatus() {
        // TODO: test PromptStatus
    }

    /**
     * Test the property 'isAnswered'
     */
    @Test
    public void isAnsweredTest() {
        // TODO: test isAnswered
    }

}
